# Generated by Django 3.1.2 on 2020-10-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teyim', '0002_auto_20201019_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
