# Generated by Django 3.1.2 on 2020-10-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teyim', '0003_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
